include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

deploystacks:
  trigger:
    include: .drupalci/.gitlab-single-pipeline.yml
    strategy: depend
  parallel:
    matrix:
      - _TARGET_CORE: ["11.0.x-dev"]
        _TARGET_PHP: [ "8.3"]
        _TARGET_DB_TYPE: "mysql"
        _TARGET_DB_VERSION: "8.4"
